name: My CICD Pipeline in Github Actions

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Initalize a repo
        run: |
          echo "This is devops Rutu"
          uname -a
    
      - name: Check The Docker Installation
        run: |
          docker
          docker images

      - name: My first step
        run: |
          docker run hello-world
